#!/bin/sh

WEBSOCKEDSCRIPTSDIR=scripts/

nohup websocketd --port=8080 --address=127.0.0.1 --passenv=PERL5LIB,PERLBREW_HOME,PERLBREW_PATH,PERLBREW_PERL,PERLBREW_ROOT,PERLBREW_VERSION,PERLBREW_MANPATH,PERLBREW_BASHRC_VERSION,PATH --reverselookup=false --maxforks=80 --dir=$WEBSOCKEDSCRIPTSDIR &
